[env]
PORT = "8000"

[tasks.mkpkg]
command = "mkdir"
args = ["-p", "www/pkg"]

[tasks.build_release]
command = "cargo"
args = ["build", "--target=wasm32-unknown-unknown", "--release"]

[tasks.bindgen]
command = "wasm-bindgen"
args = ["--out-dir", "www/pkg", "--target", "web", "target/wasm32-unknown-unknown/debug/insights2.wasm"]
dependencies = ["build"]

[tasks.bindgen_release]
command = "wasm-bindgen"
args = ["--out-dir", "www/pkg", "--target", "web", "target/wasm32-unknown-unknown/release/insights2.wasm"]
dependencies = ["build_release"]

[tasks.serve]
script = [
  '''
  cd www
  microserver -p 8000
  '''
]

[tasks.full_release]
script = [
  '''
  cd www/pkg
  wasm-opt -Oz insights2_bg.wasm -o insights2_bg.wasm
  '''
]
dependencies = ['bindgen_release']
